(cl:defpackage unit_5_services-srv
  (:use )
  (:export
   "ACTIVATE_CIRCLE_MOVEMENT"
   "<ACTIVATE_CIRCLE_MOVEMENT-REQUEST>"
   "ACTIVATE_CIRCLE_MOVEMENT-REQUEST"
   "<ACTIVATE_CIRCLE_MOVEMENT-RESPONSE>"
   "ACTIVATE_CIRCLE_MOVEMENT-RESPONSE"
  ))

