// Generated by gencpp from file unit_5_services/activate_circle_movementRequest.msg
// DO NOT EDIT!


#ifndef UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENTREQUEST_H
#define UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unit_5_services
{
template <class ContainerAllocator>
struct activate_circle_movementRequest_
{
  typedef activate_circle_movementRequest_<ContainerAllocator> Type;

  activate_circle_movementRequest_()
    : duration(0)  {
    }
  activate_circle_movementRequest_(const ContainerAllocator& _alloc)
    : duration(0)  {
  (void)_alloc;
    }



   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct activate_circle_movementRequest_

typedef ::unit_5_services::activate_circle_movementRequest_<std::allocator<void> > activate_circle_movementRequest;

typedef boost::shared_ptr< ::unit_5_services::activate_circle_movementRequest > activate_circle_movementRequestPtr;
typedef boost::shared_ptr< ::unit_5_services::activate_circle_movementRequest const> activate_circle_movementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator1> & lhs, const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator2> & rhs)
{
  return lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator1> & lhs, const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unit_5_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f60182c6a4cf2e688b1837c24d5f12e";
  }

  static const char* value(const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f60182c6a4cf2e6ULL;
  static const uint64_t static_value2 = 0x88b1837c24d5f12eULL;
};

template<class ContainerAllocator>
struct DataType< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unit_5_services/activate_circle_movementRequest";
  }

  static const char* value(const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 duration    # The time (in seconds) during which BB-8 will keep moving in circles\n"
;
  }

  static const char* value(const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct activate_circle_movementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unit_5_services::activate_circle_movementRequest_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENTREQUEST_H
