// Generated by gencpp from file unit_5_services/activate_circle_movement.msg
// DO NOT EDIT!


#ifndef UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENT_H
#define UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENT_H

#include <ros/service_traits.h>


#include <unit_5_services/activate_circle_movementRequest.h>
#include <unit_5_services/activate_circle_movementResponse.h>


namespace unit_5_services
{

struct activate_circle_movement
{

typedef activate_circle_movementRequest Request;
typedef activate_circle_movementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct activate_circle_movement
} // namespace unit_5_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unit_5_services::activate_circle_movement > {
  static const char* value()
  {
    return "b92c952a9248b3029cefe45f52f6ffde";
  }

  static const char* value(const ::unit_5_services::activate_circle_movement&) { return value(); }
};

template<>
struct DataType< ::unit_5_services::activate_circle_movement > {
  static const char* value()
  {
    return "unit_5_services/activate_circle_movement";
  }

  static const char* value(const ::unit_5_services::activate_circle_movement&) { return value(); }
};


// service_traits::MD5Sum< ::unit_5_services::activate_circle_movementRequest> should match
// service_traits::MD5Sum< ::unit_5_services::activate_circle_movement >
template<>
struct MD5Sum< ::unit_5_services::activate_circle_movementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unit_5_services::activate_circle_movement >::value();
  }
  static const char* value(const ::unit_5_services::activate_circle_movementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit_5_services::activate_circle_movementRequest> should match
// service_traits::DataType< ::unit_5_services::activate_circle_movement >
template<>
struct DataType< ::unit_5_services::activate_circle_movementRequest>
{
  static const char* value()
  {
    return DataType< ::unit_5_services::activate_circle_movement >::value();
  }
  static const char* value(const ::unit_5_services::activate_circle_movementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unit_5_services::activate_circle_movementResponse> should match
// service_traits::MD5Sum< ::unit_5_services::activate_circle_movement >
template<>
struct MD5Sum< ::unit_5_services::activate_circle_movementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unit_5_services::activate_circle_movement >::value();
  }
  static const char* value(const ::unit_5_services::activate_circle_movementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit_5_services::activate_circle_movementResponse> should match
// service_traits::DataType< ::unit_5_services::activate_circle_movement >
template<>
struct DataType< ::unit_5_services::activate_circle_movementResponse>
{
  static const char* value()
  {
    return DataType< ::unit_5_services::activate_circle_movement >::value();
  }
  static const char* value(const ::unit_5_services::activate_circle_movementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNIT_5_SERVICES_MESSAGE_ACTIVATE_CIRCLE_MOVEMENT_H
